server:
  port: 8080
  servlet:
    context-path:
spring:
  mvc:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres